name: Daily CatAPI to Slack

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 00:00 UTC 실행 (KST 오전 9시)
  workflow_dispatch:     # 수동 실행도 가능하게 함

jobs:
  post-cat-pictures:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run catapi script
        env:
          CAT_SLACK_WEBHOOK_URL: ${{ secrets.CAT_SLACK_WEBHOOK_URL }}
        run: python get_cat_pictures.py
